### ISSUE TITLE
haskell-src-1.0.2.0 does not compile with GHC 8.4.1

### ISSUE THREAD

**Issue by peti** [haskell-pkg-janitors/haskell-src#5]
~~~
Language/Haskell/Pretty.hs:236:39: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Language/Haskell/Pretty.hs:16:8-30
                             (and originally defined in ‘GHC.Base’)
                          or ‘Language.Haskell.Pretty.<>’,
                             defined at Language/Haskell/Pretty.hs:211:4
    |
236 |                      go d (e:es) = (d <> p) : go e es
    |                                       ^^

Language/Haskell/Pretty.hs:293:59: error:
    Ambiguous occurrence ‘<>’
    It could refer to either ‘Prelude.<>’,
                             imported from ‘Prelude’ at Language/Haskell/Pretty.hs:16:8-30
                             (and originally defined in ‘GHC.Base’)
                          or ‘Language.Haskell.Pretty.<>’,
                             defined at Language/Haskell/Pretty.hs:211:4
    |
293 |         pretty (HsEThingAll name)           = pretty name <> text "(..)"
    |                                                           ^^

[... many more of those ...]

Language/Haskell/ParseMonad.hs:56:10: error:
    • Could not deduce (Semigroup (ParseResult m))
        arising from the superclasses of an instance declaration
      from the context: Monoid m
        bound by the instance declaration
        at Language/Haskell/ParseMonad.hs:56:10-43
    • In the instance declaration for ‘Monoid (ParseResult m)’
   |
56 | instance Monoid m => Monoid (ParseResult m) where
   |          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
~~~

**Comment by gbaz** [comment]
@hvr this is actually going to be a blocker for the platform release...

**Comment by hvr** [comment]
@gbaz thanks for the reminder; I'll look right into this!

**Comment by hvr** [comment]
Resolved by http://hackage.haskell.org/package/haskell-src-1.0.3.0

**Comment by peti** [comment]
Thank you very much!
